<?php
define('GNMAAG_DATA1', @$_SERVER['GNMAAG_DATA1']);
define('GNMAAG_DATA2', @$_SERVER['GNMAAG_DATA2']);

define('GNMAAG_DATABASE_HOST', @$_SERVER['GNMAAG_DATABASE_HOST']);
define('GNMAAG_DATABASE_LOGIN', @$_SERVER['GNMAAG_DATABASE_LOGIN']);
define('GNMAAG_DATABASE_PASSWORD', Texto::encryptDecryptText(@$_SERVER['GNMAAG_DATABASE_PASSWORD'], false));
define('GNMAAG_DATABASE_DATABASE', @$_SERVER['GNMAAG_DATABASE_DATABASE']);

// NO REGION
define('GNMAAG_EMAIL_CONFIGURATION_NO_REGION', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_NO_REGION']);
define('GNMAAG_EMAIL_CONFIGURATION_NO_REGION_FROM', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_NO_REGION_FROM']);
define('GNMAAG_EMAIL_CONFIGURATION_NO_REGION_HOST', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_NO_REGION_HOST']);
define('GNMAAG_EMAIL_CONFIGURATION_NO_REGION_PORT', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_NO_REGION_PORT']);
define('GNMAAG_EMAIL_CONFIGURATION_NO_REGION_USERNAME', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_NO_REGION_USERNAME']);
define('GNMAAG_EMAIL_CONFIGURATION_NO_REGION_PASSWORD', Texto::encryptDecryptText(@$_SERVER['GNMAAG_EMAIL_CONFIGURATION_NO_REGION_PASSWORD']));
define('GNMAAG_EMAIL_CONFIGURATION_NO_REGION_TLS', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_NO_REGION_TLS']);

// REGION BENELUX
define('GNMAAG_EMAIL_CONFIGURATION_BENELUX', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_BENELUX']);
define('GNMAAG_EMAIL_CONFIGURATION_BENELUX_FROM', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_BENELUX_FROM']);
define('GNMAAG_EMAIL_CONFIGURATION_BENELUX_HOST', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_BENELUX_HOST']);
define('GNMAAG_EMAIL_CONFIGURATION_BENELUX_PORT', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_BENELUX_PORT']);
define('GNMAAG_EMAIL_CONFIGURATION_BENELUX_USERNAME', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_BENELUX_USERNAME']);
define('GNMAAG_EMAIL_CONFIGURATION_BENELUX_PASSWORD', Texto::encryptDecryptText(@$_SERVER['GNMAAG_EMAIL_CONFIGURATION_BENELUX_PASSWORD'], false));
define('GNMAAG_EMAIL_CONFIGURATION_BENELUX_TLS', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_BENELUX_TLS']);

// REGION UK IRELAND
define('GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND']);
define('GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_FROM', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_FROM']);
define('GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_HOST', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_HOST']);
define('GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_PORT', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_PORT']);
define('GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_USERNAME', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_USERNAME']);
define('GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_PASSWORD', Texto::encryptDecryptText(@$_SERVER['GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_PASSWORD'], false));
define('GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_TLS', @$_SERVER['GNMAAG_EMAIL_CONFIGURATION_UK_IRELAND_TLS']);

define('GNMAAG_ERROR_NOTIFICATION_EMAIL_1', @$_SERVER['GNMAAG_ERROR_NOTIFICATION_EMAIL_1']);
define('GNMAAG_ERROR_NOTIFICATION_EMAIL_2', @$_SERVER['GNMAAG_ERROR_NOTIFICATION_EMAIL_2']);
define('GNMAAG_ERROR_NOTIFICATION_EMAIL_3', @$_SERVER['GNMAAG_ERROR_NOTIFICATION_EMAIL_3']);

define('GNMAAG_AZURE_STORAGE', @$_SERVER['GNMAAG_AZURE_STORAGE']);
define('GNMAAG_AZURE_STORAGE_CONFIG_ACCOUNT_NAME', @$_SERVER['GNMAAG_AZURE_STORAGE_CONFIG_ACCOUNT_NAME']);
define('GNMAAG_AZURE_STORAGE_CONFIG_ACCOUNT_KEY', @$_SERVER['GNMAAG_AZURE_STORAGE_CONFIG_ACCOUNT_KEY']);
define('GNMAAG_AZURE_STORAGE_CONFIG_CONTAINER', @$_SERVER['GNMAAG_AZURE_STORAGE_CONFIG_CONTAINER']);
define('GNMAAG_AZURE_STORAGE_CONFIG_PRIVATE_CONTAINER', @$_SERVER['GNMAAG_AZURE_STORAGE_CONFIG_PRIVATE_CONTAINER']);
define('GNMAAG_AZURE_STORAGE_CONFIG_SAS_DURATION', @$_SERVER['GNMAAG_AZURE_STORAGE_CONFIG_SAS_DURATION']);

define('GNMAAG_SCANII_ANTIVIRUS', @$_SERVER['GNMAAG_SCANII_ANTIVIRUS']);
define('GNMAAG_SCANII_ANTIVIRUS_CONFIG_KEY', @$_SERVER['GNMAAG_SCANII_ANTIVIRUS_CONFIG_KEY']);
define('GNMAAG_SCANII_ANTIVIRUS_CONFIG_SECRET', @$_SERVER['GNMAAG_SCANII_ANTIVIRUS_CONFIG_SECRET']);

define('GNMAAG_URL_BASE', @$_SERVER['GNMAAG_URL_BASE']);

define('GNMAAG_DIRECTORY_UPDATE_DISTRIBUTORS', @$_SERVER['GNMAAG_DIRECTORY_UPDATE_DISTRIBUTORS']);
define('GNMAAG_DIRECTORY_UPDATE_GARAGES', @$_SERVER['GNMAAG_DIRECTORY_UPDATE_GARAGES']);
define('GNMAAG_DIRECTORY_UPDATE_SALES', @$_SERVER['GNMAAG_DIRECTORY_UPDATE_SALES']);
define('GNMAAG_DIRECTORY_UPDATE_SUPPLIERS', @$_SERVER['GNMAAG_DIRECTORY_UPDATE_SUPPLIERS']);
define('GNMAAG_DIRECTORY_PROCESSED', @$_SERVER['GNMAAG_DIRECTORY_PROCESSED']);

define('GNMAAG_AGN_API_URL_CONFIGURATION', @$_SERVER['GNMAAG_AGN_API_URL_CONFIGURATION']);
define('GNMAAG_AGN_API_KEY_CONFIGURATION', @$_SERVER['GNMAAG_AGN_API_KEY_CONFIGURATION']);

define('GNMAAG_LEADGEN_API_URL_CONFIGURATION', @$_SERVER['GNMAAG_LEADGEN_API_URL_CONFIGURATION']);
define('GNMAAG_LEADGEN_API_KEY_CONFIGURATION', @$_SERVER['GNMAAG_LEADGEN_API_KEY_CONFIGURATION']);

define('WEBSERVICE_PASSWORD', @$_SERVER['WEBSERVICE_PASSWORD']);
define('WEBSERVICE_USERNAME', @$_SERVER['WEBSERVICE_USERNAME']);
define('WEBSERVICE_WSDL', @$_SERVER['WEBSERVICE_WSDL']);

define('GOOGLE_API_KEY', @$_SERVER['GOOGLE_API_KEY']);
define('GOOGLE_API_KEY_REVIEWS_GV', @$_SERVER['GOOGLE_API_KEY_REVIEWS_GV']);
define('GOOGLE_API_KEY_REVIEWS_GC', @$_SERVER['GOOGLE_API_KEY_REVIEWS_GC']);

define('GNMAAG_LEADGEN_API_KEY', @$_SERVER['GNMAAG_LEADGEN_API_KEY']);
define('GNMAAG_LEADGEN_API_EMAIL', @$_SERVER['GNMAAG_LEADGEN_API_EMAIL']);

define('GNMAAG_LOBSTER_BASE_URL', @$_SERVER['GNMAAG_LOBSTER_BASE_URL']);
define('GNMAAG_LOBSTER_API_KEY', @$_SERVER['GNMAAG_LOBSTER_API_KEY']);
define('GNMAAG_LOBSTER_API_USER', @$_SERVER['GNMAAG_LOBSTER_API_USER']);

define('FEEFO_API_KEY', @$_SERVER['FEEFO_API_KEY']);
define('FEEFO_CLIENT_SECRET', @$_SERVER['FEEFO_CLIENT_SECRET']);
define('FEEFO_REQUEST_TOKEN', @$_SERVER['FEEFO_REQUEST_TOKEN']);
define('FEEFO_CLIENT_ID', @$_SERVER['FEEFO_CLIENT_ID']);
define('FEEFO_GARAGE_RATING_URL', @$_SERVER['FEEFO_GARAGE_RATING_URL']);
define('FEEFO_NETWORK_RATING_URL', @$_SERVER['FEEFO_NETWORK_RATING_URL']);
define('FEEFO_GARAGE_REVIEWS_URL', @$_SERVER['FEEFO_GARAGE_REVIEWS_URL']);
define('FEEFO_NETWORK_REVIEWS_URL', @$_SERVER['FEEFO_NETWORK_REVIEWS_URL']);
define('FEEFO_REQUEST_REVIEW_URL', @$_SERVER['FEEFO_REQUEST_REVIEW_URL']);

define('GNMAAG_GNM_API_KEY', @$_SERVER['GNMAAG_GNM_API_KEY']);
define('GNMAAG_GNM_API_USER', @$_SERVER['GNMAAG_GNM_API_USER']);
define('GNMAAG_GNM_API_KEY2', @$_SERVER['GNMAAG_GNM_API_KEY2']);
define('GNMAAG_GNM_API_USER2', @$_SERVER['GNMAAG_GNM_API_USER2']);

define('GNMAAG_AGN_API_KEY', @$_SERVER['GNMAAG_AGN_API_KEY']);
define('GNMAAG_AGN_API_EMAIL', @$_SERVER['GNMAAG_AGN_API_EMAIL']);

define('CLOUDFLARE_SECRET_KEY', @$_SERVER['CLOUDFLARE_SECRET_KEY']);

define('SFTP_PASSWORD', @$_SERVER['SFTP_PASSWORD']);
define('SFTP_USERNAME', @$_SERVER['SFTP_USERNAME']);
define('SFTP_REMOTE', @$_SERVER['SFTP_REMOTE']);
define('SFTP_REMOTE_DB', @$_SERVER['SFTP_REMOTE_DB']);
define('SFTP_DISTRIBUTOR_IMPORT', @$_SERVER['SFTP_DISTRIBUTOR_IMPORT']);

define('REPAIR_MAINTENANCE_KEY', @$_SERVER['REPAIR_MAINTENANCE_KEY']);
define('REPAIR_MAINTENANCE_GNM_CONNECTION_KEY', @$_SERVER['REPAIR_MAINTENANCE_GNM_CONNECTION_KEY']);
define('REPAIR_MAINTENANCE_SEND_DATA', @$_SERVER['REPAIR_MAINTENANCE_SEND_DATA']);
define('REPAIR_MAINTENANCE_DATA_1', @$_SERVER['REPAIR_MAINTENANCE_DATA_1']);
define('REPAIR_MAINTENANCE_DATA_2', @$_SERVER['REPAIR_MAINTENANCE_DATA_2']);

define('CONFERENCES_EXPORT_LIMIT', @$_SERVER['CONFERENCES_EXPORT_LIMIT']);
define('CONFERENCES_DELEGATES_EXPORT_LIMIT', @$_SERVER['CONFERENCES_DELEGATES_EXPORT_LIMIT']);
define('GARAGES_EXPORT_LIMIT', @$_SERVER['GARAGES_EXPORT_LIMIT']);
define('DISTRIBUTORS_EXPORT_LIMIT', @$_SERVER['DISTRIBUTORS_EXPORT_LIMIT']);
define('DELEGATES_EXPORT_LIMIT', @$_SERVER['DELEGATES_EXPORT_LIMIT']);
define('TRAININGS_EXPORT_LIMIT', @$_SERVER['TRAININGS_EXPORT_LIMIT']);
define('VENUES_EXPORT_LIMIT', @$_SERVER['VENUES_EXPORT_LIMIT']);
define('DEFAULT_NETWORK_FLEETS', @$_SERVER['DEFAULT_NETWORK_FLEETS']);

define('LEADGEN_EMAILS_SEND_TO_REAL_EMAILS', @$_SERVER['LEADGEN_EMAILS_SEND_TO_REAL_EMAILS']);
define('LEADGEN_EMAILS_DEFAULT_EMAIL', @$_SERVER['LEADGEN_EMAILS_DEFAULT_EMAIL']);

define('SENDGRID_EMAIL_SEND_TO_REAL_RECIPIENT', @$_SERVER['SENDGRID_EMAIL_SEND_TO_REAL_RECIPIENT']);
define('SENDGRID_EMAIL_DEFAULT_EMAILS', @$_SERVER['SENDGRID_EMAIL_DEFAULT_EMAILS']);
define('SENDGRID_EMAIL_SHOW_MAINTENANCE_CONFIG', @$_SERVER['SENDGRID_EMAIL_SHOW_MAINTENANCE_CONFIG']);

define('TOKEN_AUTOMATIC_TEST', @$_SERVER['TOKEN_AUTOMATIC_TEST']);

define('GOOGLE_TAG_MANAGER_ID', @$_SERVER['GOOGLE_TAG_MANAGER_ID']);

define('VERSION_CACHE', @$_SERVER['VERSION_CACHE']);

define('CLOUDFLARE_SITE_KEY', @$_SERVER['CLOUDFLARE_SITE_KEY']);
define('CLOUDFLARE_CONFIG_ACTIVE', @$_SERVER['CLOUDFLARE_CONFIG_ACTIVE']);

define('SHORTNER_API_KEY', @$_SERVER['SHORTNER_API_KEY']);
define('SHORTNER_DEFAULT_DOMAIN', @$_SERVER['SHORTNER_DEFAULT_DOMAIN']);

define('DEBUG', @$_SERVER['DEBUG']);

define('NETWORK_ID_AUTOCARE', @$_SERVER['NETWORK_ID_AUTOCARE']);
define('NETWORK_ID_AGN', @$_SERVER['NETWORK_ID_AGN']);
define('NETWORK_ID_TOPTRUCK', @$_SERVER['NETWORK_ID_TOPTRUCK']);
define('NETWORK_ID_UNITED_GARAGE_SERVICE', @$_SERVER['NETWORK_ID_UNITED_GARAGE_SERVICE']);
define('NETWORK_ID_GEXPERT', @$_SERVER['NETWORK_ID_GEXPERT']);
define('NETWORK_ID_GV', @$_SERVER['NETWORK_ID_GV']);
define('NETWORK_ID_GC', @$_SERVER['NETWORK_ID_GC']);
define('NETWORK_ID_LEASEPROF', @$_SERVER['NETWORK_ID_LEASEPROF']);

define('TINY_API_KEY', @$_SERVER['TINY_API_KEY']);

define('NETWORKS_WEB_LOGIN_PREFIX_AGN', @$_SERVER['NETWORKS_WEB_LOGIN_PREFIX_AGN']);
define('NETWORKS_WEB_LOGIN_PREFIX_GV', @$_SERVER['NETWORKS_WEB_LOGIN_PREFIX_GV']);
define('NETWORKS_WEB_LOGIN_PREFIX_GC', @$_SERVER['NETWORKS_WEB_LOGIN_PREFIX_GC']);

define('JWT_CODE_WORD', @$_SERVER['JWT_CODE_WORD']);
define('KEY_TOKEN', @$_SERVER['KEY_TOKEN']);

define('CRON_ACTIVE', @$_SERVER['CRON_ACTIVE']);
define('CRON_DEBUG_ACTIVE', @$_SERVER['CRON_DEBUG_ACTIVE']);

define('SMS_ACTIVE', @$_SERVER['SMS_ACTIVE']);
define('TINY_IMPROVE_PERCENTAGE', @$_SERVER['TINY_IMPROVE_PERCENTAGE']);

define('GNM_AAG_UNSENT_EMAILS_TOKEN', @$_SERVER['GNM_AAG_UNSENT_EMAILS_TOKEN']);
define('GNM_AAG_UNSENT_EMAILS_TO', @$_SERVER['GNM_AAG_UNSENT_EMAILS_TO']);
define('GNM_AAG_UNSENT_EMAILS_FROM', @$_SERVER['GNM_AAG_UNSENT_EMAILS_FROM']);
define('GNM_AAG_UNSENT_EMAILS_MAX', @$_SERVER['GNM_AAG_UNSENT_EMAILS_MAX']);

define('ENVIRONMENT_PRO', @$_SERVER['ENVIRONMENT_PRO']);
define('PRIVACY_NOTICE_CODE_UK', @$_SERVER['PRIVACY_NOTICE_CODE_UK']);
define('PRIVACY_NOTICE_CODE_BEN', @$_SERVER['PRIVACY_NOTICE_CODE_BEN']);
define('PRIVACY_NOTICE_SETTINGS_CODE', @$_SERVER['PRIVACY_NOTICE_SETTINGS_CODE']);

define('SERVER_NAME', @$_SERVER['SERVER_NAME']);

define('GNMAAG_BCC', @$_SERVER['GNMAAG_BCC']);
define('GNMAAG_WEBS_BCC', @$_SERVER['GNMAAG_BCC']);
